# Generated by Django 5.1.5 on 2025-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
