# Generated by Django 5.1.5 on 2025-01-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_alter_revenue_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='revenue',
            new_name='amount',
        ),
    ]
